name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install
      
    - name: linting typescript
      run: npm run lint:ts

    - name: linting scss
      run: npm run lint:scss

    - name: testing unit
      run: npm run test:unit

    - name: build project production
      run: npm run build:prod

